# Generated by Django 5.2.8 on 2026-05-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
