# Generated by Django 5.2.8 on 2026-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_weeklysalaryrecord_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
