# Generated by Django 5.2.8 on 2026-06-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_categorymodel_latitude_categorymodel_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
