# Generated by Django 5.2.8 on 2026-06-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_categorymodel_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='type',
            new_name='deliveryTime',
        ),
    ]
