# Generated by Django 5.2.8 on 2026-06-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_rename_type_categorymodel_deliverytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
