# Generated by Django 5.2.8 on 2026-06-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_profile_address_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('prepaid', 'Prepaid (Screenshot)'), ('cod', 'Pay on Delivery')], default='prepaid', max_length=20),
        ),
    ]
