# Generated by Django 5.2.8 on 2026-06-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_giveaway'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giveaway',
            options={'ordering': ['-round']},
        ),
        migrations.RemoveField(
            model_name='giveaway',
            name='deliverd_orders',
        ),
        migrations.AddField(
            model_name='giveaway',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='delivered_orders',
            field=models.ManyToManyField(blank=True, related_name='giveaways', to='delivery.order'),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='price',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='round',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giveaway_wins', to='delivery.profile'),
        ),
    ]
