# Generated by Django 5.2.8 on 2026-07-01 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_alter_giveaway_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giveaway',
            options={'ordering': ['-completed_at']},
        ),
        migrations.RemoveField(
            model_name='giveaway',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='giveaway',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='giveaway',
            name='round',
        ),
        migrations.AddField(
            model_name='giveaway',
            name='milestone',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='order',
            name='counted_for_giveaway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='giveaway_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='giveaway_wins_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giveaway_wins', to='delivery.profile'),
        ),
    ]
