# Generated by Django 5.2.8 on 2026-07-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_alter_giveaway_options_remove_giveaway_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinWheelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_key', models.CharField(max_length=20)),
                ('prize_label', models.CharField(max_length=100)),
                ('prize_value', models.PositiveIntegerField(default=0)),
                ('order_count_at_spin', models.PositiveIntegerField(default=0)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_results', to='delivery.profile')),
            ],
            options={
                'ordering': ['-spun_at'],
            },
        ),
    ]
