# Generated by Django 5.2.8 on 2026-08-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_spinwheelresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('coins', 'Coins'), ('extra_spin', 'Extra Spin'), ('lose_all', 'Lose All')], default='coins', max_length=20)),
                ('value', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#FF5722', max_length=20)),
                ('probability', models.DecimalField(decimal_places=2, default=0, help_text="Relative weight / percent chance of landing on this prize. Doesn't need to sum to exactly 100 — it's used as a weight.", max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text="Position on the wheel (0-based). Must match the frontend's segment order.")),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='spinwheelresult',
            name='order_count_at_spin',
        ),
        migrations.RemoveField(
            model_name='spinwheelresult',
            name='prize_key',
        ),
        migrations.RemoveField(
            model_name='spinwheelresult',
            name='prize_label',
        ),
        migrations.RemoveField(
            model_name='spinwheelresult',
            name='prize_value',
        ),
        migrations.AddField(
            model_name='order',
            name='spin_chance_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='available_spins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spinwheelresult',
            name='coins_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spinwheelresult',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The delivered order whose chance was spent on this spin, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_result', to='delivery.order'),
        ),
        migrations.AddField(
            model_name='spinwheelresult',
            name='status',
            field=models.CharField(choices=[('not_received', 'Not Received'), ('received', 'Received')], default='not_received', max_length=20),
        ),
        migrations.AddField(
            model_name='spinwheelresult',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='delivery.spinprize'),
        ),
    ]
