# Generated by Django 5.2.8 on 2026-08-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_spinprize_remove_spinwheelresult_order_count_at_spin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free_delivery_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spinprize',
            name='spin_count',
            field=models.PositiveIntegerField(default=1, help_text="Only used for kind='extra_spin' — how many spins this prize grants."),
        ),
        migrations.AddField(
            model_name='spinwheelresult',
            name='free_delivery_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spinwheelresult',
            name='spins_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spinprize',
            name='kind',
            field=models.CharField(choices=[('coins', 'Coins'), ('extra_spin', 'Extra Spin Chance'), ('free_delivery', 'Free Delivery'), ('thanks', 'Thanks for Playing')], default='coins', max_length=20),
        ),
        migrations.AlterField(
            model_name='spinprize',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spinprize',
            name='probability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
