# Generated by Django 5.2.8 on 2026-09-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_profile_free_delivery_credits_spinprize_spin_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal label only — not sent to users.', max_length=100)),
                ('message', models.TextField(help_text='Telegram Markdown supported (*bold*, _italic_, etc.)')),
                ('target', models.CharField(choices=[('all', 'Everyone'), ('customers', 'Customers only'), ('delivery', 'Delivery staff only')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='owner_notified_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
